DROP TABLE "TBL_VOTE";
DROP TABLE "TBL_GRADE";
DROP TABLE "TBL_MEMBER";
DROP TABLE "TBL_PARTY";

CREATE TABLE "TBL_PARTY" (
	"P_CODE"	CHAR(2)		NOT NULL,
	"P_NAME"	VARCHAR2(20)		NULL,
	"P_INDATE"	DATE		NULL,
	"P_LEADER"	VARCHAR2(20)		NULL,
	"P_TEL1"	CHAR(3)		NULL,
	"P_TEL2"	CHAR(4)		NULL,
	"P_TEL3"	CHAR(4)		NULL
);
COMMENT ON COLUMN "TBL_PARTY"."P_CODE" IS '정당 코드';
COMMENT ON COLUMN "TBL_PARTY"."P_NAME" IS '명칭';
COMMENT ON COLUMN "TBL_PARTY"."P_INDATE" IS '등록년월일';
COMMENT ON COLUMN "TBL_PARTY"."P_LEADER" IS '대표자';
COMMENT ON COLUMN "TBL_PARTY"."P_TEL1" IS '전화번호1';
COMMENT ON COLUMN "TBL_PARTY"."P_TEL2" IS '전화번호2';
COMMENT ON COLUMN "TBL_PARTY"."P_TEL3" IS '전화번호3';

CREATE TABLE "TBL_MEMBER" (
	"M_NO"	CHAR(1)		NOT NULL,
	"M_NAME"	VARCHAR2(20)		NULL,
	"M_JUMIN"	CHAR(13)		NULL,
	"P_SCHOOL"	CHAR(1)		NULL,
	"M_CITY"	VARCHAR2(20)		NULL,
	"P_CODE"	CHAR(2)		NOT NULL
);
COMMENT ON COLUMN "TBL_MEMBER"."M_NO" IS '후보 번호';
COMMENT ON COLUMN "TBL_MEMBER"."M_NAME" IS '성명';
COMMENT ON COLUMN "TBL_MEMBER"."M_JUMIN" IS '후보자 주민번호';
COMMENT ON COLUMN "TBL_MEMBER"."P_SCHOOL" IS '최종학력';
COMMENT ON COLUMN "TBL_MEMBER"."M_CITY" IS '지역구';
COMMENT ON COLUMN "TBL_MEMBER"."P_CODE" IS '소속 정당';

CREATE TABLE "TBL_VOTE" (
	"V_JUMIN"	CHAR(13)		NOT NULL,
	"V_NAME"	VARCHAR2(20)		NULL,
	"V_TIME"	CHAR(4)		NULL,
	"V_AREA"	CHAR(20)		NULL,
	"V_CONFIRM"	CHAR(1)		NULL,
	"M_NO"	CHAR(1)		NOT NULL
);
COMMENT ON COLUMN "TBL_VOTE"."V_JUMIN" IS '투표자 주민번호';
COMMENT ON COLUMN "TBL_VOTE"."V_NAME" IS '성명';
COMMENT ON COLUMN "TBL_VOTE"."V_TIME" IS '투표 시간';
COMMENT ON COLUMN "TBL_VOTE"."V_AREA" IS '투표 장소';
COMMENT ON COLUMN "TBL_VOTE"."V_CONFIRM" IS '유권자 확인';
COMMENT ON COLUMN "TBL_VOTE"."M_NO" IS '후보 번호';


CREATE TABLE "TBL_GRADE" (
	"M_NO"	CHAR(1)		NOT NULL,
	"G_DATE"	DATE		NULL,
	"G_SCHOOL_NAME"	VARCHAR2(20)		NULL
);
COMMENT ON COLUMN "TBL_GRADE"."M_NO" IS '후보 번호';
COMMENT ON COLUMN "TBL_GRADE"."G_DATE" IS '졸업년월일';
COMMENT ON COLUMN "TBL_GRADE"."G_SCHOOL_NAME" IS '졸업학교명';

ALTER TABLE "TBL_VOTE" ADD CONSTRAINT "PK_TBL_VOTE" PRIMARY KEY (
	"V_JUMIN"
);

ALTER TABLE "TBL_MEMBER" ADD CONSTRAINT "PK_TBL_MEMBER" PRIMARY KEY (
	"M_NO"
);

ALTER TABLE "TBL_PARTY" ADD CONSTRAINT "PK_TBL_PARTY" PRIMARY KEY (
	"P_CODE"
);

ALTER TABLE "TBL_GRADE" ADD CONSTRAINT "PK_TBL_GRADE" PRIMARY KEY (
	"M_NO"
);

ALTER TABLE "TBL_VOTE" ADD CONSTRAINT "FK_TBL_MEMBER_TO_TBL_VOTE_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "TBL_MEMBER" (
	"M_NO"
);

ALTER TABLE "TBL_MEMBER" ADD CONSTRAINT "FK_TBL_PARTY_TO_TBL_MEMBER_1" FOREIGN KEY (
	"P_CODE"
)
REFERENCES "TBL_PARTY" (
	"P_CODE"
);

ALTER TABLE "TBL_GRADE" ADD CONSTRAINT "FK_TBL_MEMBER_TO_TBL_GRADE_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "TBL_MEMBER" (
	"M_NO"
);




INSERT INTO TBL_PARTY ( P_CODE, P_NAME, P_INDATE, P_LEADER, P_TEL1, P_TEL2, P_TEL3)
    VALUES ('P1', 'A정당', '2010-01-01', '위대표', '02', '1111', '0001');
INSERT INTO TBL_PARTY ( P_CODE, P_NAME, P_INDATE, P_LEADER, P_TEL1, P_TEL2, P_TEL3)
    VALUES ('P2', 'B정당', '2010-02-01', '명대표', '02', '1111' ,'0002');


INSERT INTO TBL_MEMBER ( M_NO, M_NAME, P_CODE, P_SCHOOL, M_JUMIN, M_CITY)
    VALUES ('1', '김후보', 'P1', '1', '6603011999991', '수선화동');
INSERT INTO TBL_MEMBER ( M_NO, M_NAME, P_CODE, P_SCHOOL, M_JUMIN, M_CITY)
    VALUES ('2', '이후보', 'P2', '3', '5503011999992', '민들래동');


INSERT INTO TBL_VOTE ( V_JUMIN, V_NAME, V_TIME, V_AREA, V_CONFIRM, M_NO)
    VALUES('9901011000100', '김유권', '0930', '제1투표장', 'N', '1');
INSERT INTO TBL_VOTE ( V_JUMIN, V_NAME, V_TIME, V_AREA, V_CONFIRM, M_NO)
    VALUES('8901012000200', '이유권', '0930', '제1투표장', 'N', '2');
    
    
INSERT INTO TBL_GRADE ( M_NO, G_DATE, G_SCHOOL_NAME)
    VALUES ('1', '1987-03-04', '역삼고등학교');
INSERT INTO TBL_GRADE ( M_NO, G_DATE, G_SCHOOL_NAME)
    VALUES ('2', '1989-05-03', 'KH대학원');
    
COMMIT;